---
shell:
  name: "Network Tester Interactive"
  version: "2.2.21"
  slug: "net_test"
  description: >
    A tool to begin testing your network, with
    standard tools like ping, traceroute.\n
    This provides additonal logging capabilities for
    historical view.\n
    Additional tests like speedtest and iperf
    are included.\n

tester:
  name: "NetworkTesterBackend"
  version: "2.2.1"
  slug: "tester"
  description: >
    A backend library to enable testing of the network.\n
    It uses builtin linux commands to run tests,\n
    and logs to database.

gui:
  name: "Toolset Launcher"
  version: "0.01"
  slug: "ts_gui"

cli_script:
  name: "flamegrid"
  version: "1.0.0-alpha"
  slug: "flamegrid"
  description: >
    A command line script interfacing with the Tester class,
    as an alternative to the shell.
    Uses google's python flame library.

logger:
  name: "Nike Log Storage Engine"
  version: "0.0.2"
  slug: "nikelog"
  descripton: >
    Logging engine designed to store performance data,
    in a consumable format for time based analysis.

default:
  targets:
    - 1.1.1.1
    - 4.4.4.4
    - 8.8.8.8
    - 3.us.pool.ntp.org
  base_path: "network-testing"
  sleep_interval_seconds: 60
