---
shell:
  name: "Network Tester Interactive"
  version: "2.0-alpha"
  slug: "net_test"
  description: >
    A tool to begin testing your network, with
    standard tools like ping, traceroute.\n
    This provides additonal logging capabilities for
    historical view.\n
    Additional tests like speedtest and iperf
    are included.\n

tester:
  name: "Network Tester Backend"
  version: "1.0-alpha"
  slug: "tester"

gui:
  name: "Toolset Launcher"
  version: "0.01"
  slug: "ts_gui"

default:
  targets:
    - 1.1.1.1
    - 8.8.8.8
    - 3.us.pool.ntp.org
  base_path: "network-testing"
  
